[tool.pylint.format]
max-line-length = 120

# [tool.pylint.tool-check]
# generated-members = 'self.exit_codes.*'

[tool.pylint.messages_control]
disable = [
    'bad-continuation',
    'duplicate-code',
    'locally-disabled',
    'logging-format-interpolation',
    'inconsistent-return-statements',
    'import-outside-toplevel',
    'no-else-raise',
    'too-many-arguments',
    'too-many-ancestors',
    'too-many-branches',
    'too-many-locals',
    'logging-fstring-interpolation'
]

[tool.pylint.basic]
good-names = [
    'i',
    'j',
    'k',
]

[tool.isort]
line_length = 120
