name: parsevasp

on: [push, pull_request]

jobs:
  # pre-commit:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   strategy:
  #     matrix:
  #       python: ['3.8']
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python }}
  #     - name: Upgrade pip
  #       run: |
  #         pip install --upgrade pip
  #         pip --version
  #     - name: Install parsevasp
  #       run:
  #         pip install -e .[dev]
  #         pip freeze
  #     - name: Run pre-commit
  #       run: pre-commit run --all-files || ( git diff; git status; exit 1; )
  tests:
    #needs: [pre-commit]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip
        run: |
          pip install --upgrade pip
          pip --version
      - name: Install Tox
        run: pip install tox
      - name: Install parsevasp
        run: |
          pip install -e .[dev]
          pip freeze
      - name: Remove dot in Python version for passing version to tox
        uses: frabert/replace-string-action@master
        id: tox
        with:
          pattern: '\.'
          string: ${{ matrix.python }}
          replace-with: ''
      - name: Run tox
        run: tox -e py${{ steps.tox.outputs.replaced }}-parsevasp
      - name: Run coverage from coverage-python by running pytest yet again
        if: ${{ matrix.python }} == '3.9'
        run: pytest --cov-report=xml --cov-append --cov=parsevasp
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: parsevasp
          fail_ci_if_error: true
